version: "3.9" 

services:
  app:
    build:
      context:  .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command:  "python3 manage.py runserver 0.0.0.0:80"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes: 
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
  dev-static-data: 