# Generated by Django 5.1.3 on 2024-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'IN_PROCESS'), (1, 'COMPLETED'), (2, 'CANCELED')], default=0)),
                ('finished', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
